### ISSUE TITLE
Open Source 101

### ISSUE THREAD

**Issue by skidlamer** [ZeWhiteHatHacker/latest_krunker_hack#2]
Dude instead of re-uploading my source and then pretending you wrote it, why don't you  actually fork it and if you have any improvements request a pull. It's how open source works and how many different developers with different ideas come together and create something beautiful. Give it a shot m8. ;)

**Comment by ZeWhiteHatHacker** [comment]
yea im sorry man but i actuall writ a whole script ages ago took me weeks and just insta patched 2 weeks after release so
